version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CRAWL4AI_API_KEY=${CRAWL4AI_API_KEY}
    depends_on:
      - redis
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs